FROM python:3.11

WORKDIR /

COPY matchmaker/requirements.txt requirements.txt

RUN apt update && apt install libpq-dev -y
RUN pip install --no-cache-dir --upgrade -r requirements.txt

COPY matchmaker/ app
COPY webserver/utils/ app/utils

WORKDIR /app

ENTRYPOINT ["python3", "/app/main.py"]
