version: '3'
services:
  db:
    build:
      context: app/utils/postgres
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file:
      - app/utils/postgres/postgres.env
  pgbackups:
    image: prodrigestivill/postgres-backup-local
    restart: always
    user: postgres:postgres
    volumes:
      - /var/opt/pgbackups:/backups
    links:
      - db
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_EXTRA_OPTS=-Z6 --schema=public --blobs
      - SCHEDULE=@every 0h15m00s
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=8080
    env_file:
      - app/utils/postgres/postgres.env
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
  redis:
    image: redis:7-alpine
    restart: unless-stopped
  csgo_manager:
    depends_on:
      - db
      - redis
    build:
      context: app
      dockerfile: Dockerfile
    volumes:
      - ./gslt.json:/app/gslt.json
      - ./demofiles:/demofiles
      - ./backupfiles:/backupfiles
    ports:
      - 80:80
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - MAX_WORKERS=10
    env_file:
      - ./webserver.env
  telegram_bot:
    depends_on:
      - csgo_manager
    build:
      context: telegram_bot
      dockerfile: Dockerfile
    env_file:
      - telegram_bot/.env
