version: '3'
services:
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file:
      - webserver/utils/postgres/postgres.env
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
  redis:
    image: redis:7-alpine
    restart: unless-stopped
  csgo_manager:
    depends_on:
      - db
      - redis
    build:
      context: webserver
      dockerfile: Dockerfile
    volumes:
      - ./gslt.json:/app/gslt.json
      - ./demofiles:/demofiles
      - ./backupfiles:/backupfiles
    ports:
      - 80:80
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - MAX_WORKERS=10
  telegram_bot:
    depends_on:
      - csgo_manager
    build:
      context: telegram_bot
      dockerfile: Dockerfile
    env_file:
      - telegram_bot/.env
