FROM tiangolo/uvicorn-gunicorn-fastapi:python3.11

WORKDIR /

COPY webserver/requirements.txt requirements.txt

RUN apt update && apt install libpq-dev -y
RUN pip install --no-cache-dir --upgrade -r requirements.txt

COPY worker/ app
COPY webserver/endpoints/ app/endpoints
COPY webserver/utils/ app/utils
COPY webserver/templates/ app/templates

WORKDIR /app

ENV PORT=8080
EXPOSE 8080 8080
