version: '3'
services:
  csgo_manager:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./teams.json:/app/teams.json
      - ./gslt.json:/app/gslt.json
      - ./demofiles:/demofiles
      - ./backupfiles:/backupfiles
    ports:
      - 80:80
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - MAX_WORKERS=10
    env_file:
      - ./slave.env